//! Standard implementation of `barrique` binary serialization format
//!
//! `barrique` is a serialization format designed for local out-of-memory
//! caches, featuring metadata, compression and streaming. Data stored in
//! the core primitive — region. Regions are LZ4 compressed blocks
//! of encoded bytes additionally storing small metadata header.
//!
//! # Example
//!
//! Most likely you'll start with implementations generated by derive macro:
//!
//! ```
//! use barrique::region::{Size, Seed};
//! use barrique::{Encode, Decode};
//! use barrique::frame::Frame;
//!
//! #[derive(Encode, Decode, Clone, Debug, PartialEq)]
//! struct Bee {
//!     name: String,
//!     state: State,
//!     #[barrique(skip(default_expr = "2"))]
//!     age: u8,
//! }
//!
//! #[derive(Encode, Decode, Clone, Debug, PartialEq)]
//! #[barrique(tag_repr = "u8")]
//! enum State {
//!     Collecting(i32, i32),
//!     Buzzing {
//!         sound_level: u8
//!     },
//!     Sleeping
//! }
//!
//! let bee = Bee {
//!     name: "Oh, hey!".to_string(),
//!     state: State::Sleeping,
//!     age: 2
//! };
//! let mut dst = vec![];
//!
//! let frame = Frame::new(&mut dst, Seed::new(0))
//!     .with_label("A beehive".try_into().unwrap());
//! frame.encode(bee.clone()).unwrap();
//!
//! let frame: Frame<Bee, _> = Frame::decode(dst.as_slice(), Seed::new(0))
//!     .expect("Failed to open a frame");
//!
//! assert_eq!(frame.get_value(Size::default()).unwrap(), bee);
//! ```
//!
//! `Frame` is specification-defined format wrapping a stream primitive. Streams
//! available as `StreamEncoder` and `StreamDecoder`.
//!
//! # Streaming
//!
//! `barrique` format was designed to keep buffer memory usage constant, which is
//! 128 KiB (`Size` allows to specify it if a value to encode is less
//! than 128 KiB). The buffer size limit is exact length of two raw regions,
//! previous region is stored to improve LZ4 compression ratio, which
//! maximum window size is 64 KiB.
//!
//! The crate provides a wrapper for `std::io::Write` and `std::io::Read` traits
//! called `CursorView` in order to utilize streaming, making memory usage up to 192 KiB
//! where 128 KiB allocated by the stream primitive and additional 64 KiB is the maximum
//! size of dynamic buffer of a `CursorView` (although it can be more than 64 KiB, stream
//! primitive requests up to 64 KiB per request).
//!
//! An example of `CursorView` application:
//!
//! ```rust, no_run
//! use barrique::encode::{StreamEncoder, Encode};
//! use barrique::region::{Size, Seed};
//! use barrique::cursor::CursorView;
//!
//! use std::fs::File;
//!
//! let file = File::create("serialized.bin").unwrap();
//! let mut dst = CursorView::new(file);
//!
//! let mut encoder = StreamEncoder::new(&mut dst, Seed::new(0), Size::full());
//! <str as Encode>::encode(&mut encoder, "Hello, world!").unwrap();
//!
//! encoder.flush().unwrap(); // Buffer -> `dst`
//! dst.flush().unwrap(); // `dst` -> File
//! ```
//!
//! # `no_std` support
//!
//! Available via `no_std` feature, however, `alloc` crate is required

#![cfg_attr(not(feature = "std"), no_std)]

// Underlying C implementation of LZ4 depends on allocation unless specific preprocessor
// definition is stated, which is impossible with current bindings. Either way pushing
// 128 KiB size RegionBuffer to the stack is a little bit unsuitable
extern crate alloc;

#[cfg(feature = "derive")]
pub use barrique_derive::{Encode, Decode};
pub(crate) use barrique_derive::tuple_drop_guard;

pub mod cursor;
pub mod decode;
pub mod encode;
pub mod frame;
pub mod r#impl;
pub mod region;

mod lz4;

#[cfg(test)]
mod tests {
    use std::mem::MaybeUninit;
    use crate::decode::{Decode, StreamDecoder};
    use crate::encode::{Encode, StreamEncoder};
    use crate::frame::Frame;
    use crate::region::{Size, Push, RegionBuffer, Seed};

    #[test]
    fn back_and_forth() {
        let sample = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
        let mut dst = vec![];

        let mut encoder = StreamEncoder::new(
            &mut dst,
            Seed::new(0),
            Size::default()
        );

        Encode::encode(&mut encoder, &sample).unwrap();
        encoder.flush().unwrap();

        let mut decoder = StreamDecoder::new(
            dst.as_slice(),
            Seed::new(0),
            Size::default()
        ).unwrap();

        let mut value = MaybeUninit::uninit();
        <[i32; 10] as Decode>::decode(&mut decoder, &mut value).unwrap();
        assert_eq!(unsafe { value.assume_init() }, sample);
    }

    #[test]
    fn frame_back_and_forth() {
        let sample = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
        let mut dst = vec![];

        let frame = Frame::new(&mut dst, Seed::new(0));
        frame.encode(sample).unwrap();

        let frame = Frame::<[i32; 10], _>::decode(dst.as_slice(), Seed::new(0)).unwrap();
        assert_eq!(frame.get_value(Size::default()).unwrap(), sample);
    }

    #[test]
    fn frame_metadata() {
        let mut dst = vec![];

        let frame = Frame::<(), _>::new(&mut dst, Default::default())
            .with_label("A snack".try_into().unwrap())
            .with_timestamp(u64::MAX);
        frame.encode(()).unwrap();

        let frame = Frame::<(), _>::decode(dst.as_slice(), Default::default()).unwrap();

        assert_eq!(frame.get_label().unwrap().as_str(), "A snack");
        assert_eq!(frame.get_timestamp().unwrap(), u64::MAX);
    }

    #[test]
    fn assert_region_static() {
        let sample = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
        let serialized_static
            = [11, 0, 10, 0, 89, 50, 109, 105, 206, 198, 199, 29, 160, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

        let mut dst = vec![];
        let mut authority = Push::new(&mut dst, Seed::new(0));

        let mut region = RegionBuffer::new(Size::default().cap());
        region.write(&sample);
        region.pass(&mut authority).unwrap();

        assert_eq!(dst, serialized_static);
    }
}